apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.argoproj.io
spec:
  group: argoproj.io
  scope: Namespaced
  version: v1alpha1
  names:
    kind: Workflow
    plural: workflows
    shortNames:
      - wf
